services:
  admin:
    build: .
    container_name: synergazing-admin-prod
    restart: unless-stopped
    volumes:
      - admin-storage-prod:/var/www/html/storage/app/public
      - ./.env:/var/www/html/.env
    environment:
      - APP_ENV=production
      - APP_URL=https://admin.synergazing.app
      - DB_CONNECTION=pgsql
      - DB_HOST=synergazing-db-prod
      - DB_PORT=5432
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - AUTORUN_ENABLED=true
      - AUTORUN_LARAVEL_MIGRATION=false
      - LOG_CHANNEL=stderr
    networks:
      - caddy_net_external

networks:
  caddy_net_external:
    external: true
    name: caddy_net

volumes:
  admin-storage-prod: