services:
  admin:
    build: .
    container_name: synergazing-admin-prod
    restart: unless-stopped
    environment:
      - APP_ENV=production
      - APP_URL=https://admin.synergazing.app
      # Koneksi ke DB PROD
      - DB_CONNECTION=pgsql
      - DB_HOST=synergazing-db-prod
      - DB_PORT=5432
      - DB_DATABASE=${DB_DATABASE} # (Pastikan sama dgn Backend Prod)
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - AUTORUN_ENABLED=true
    networks:
      - caddy_net_external

networks:
  caddy_net_external:
    external: true
    name: caddy_net