services:
  admin:
    build: .
    container_name: synergazing-admin
    restart: unless-stopped
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_KEY=${APP_KEY}
      - APP_URL=https://admin.synergazing.app
      
      # KONEKSI DATABASE (Nembak ke container Backend)
      - DB_CONNECTION=pgsql
      - DB_HOST=synergazing-db    # <--- Nama container DB di project backend
      - DB_PORT=5432
      - DB_DATABASE=${DB_NAME}    # Pastikan nama DB sama dengan Backend
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      
      # Settings untuk Image Serversideup
      - PHP_OPCACHE_ENABLE=1
      - AUTORUN_ENABLED=true      # Otomatis jalankan migrasi & cache saat start
    networks:
      - caddy_net_external

networks:
  caddy_net_external:
    external: true
    name: caddy_net