services:
  admin:
    build: .
    container_name: synergazing-admin-prod
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 384M
    environment:
      - APP_ENV=production
      - APP_URL=https://admin.synergazing.app
      - DB_CONNECTION=pgsql
      - DB_HOST=synergazing-db-prod
      - DB_PORT=5432
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - AUTORUN_ENABLED=true
    networks:
      - caddy_net_external

networks:
  caddy_net_external:
    external: true
    name: caddy_net