services:
  admin:
    build: .
    container_name: synergazing-admin-dev
    restart: unless-stopped
    environment:
      - APP_ENV=local
      - APP_URL=https://dev-admin.synergazing.app
      - DB_CONNECTION=pgsql
      - DB_HOST=synergazing-db-dev    
      - DB_PORT=5432
      - DB_DATABASE=synergazing_dev 
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - caddy_net_external
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M

networks:
  caddy_net_external:
    external: true
    name: caddy_net